global:
  scrape_interval: 15s #Scrape interval to every 15 seconds.
  evaluation_interval: 15s #Evaluate rules every 15 seconds.

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: [ "localhost:9090" ]

  - job_name: "cadvisor"
    static_configs:
      - targets: [ "cadvisor:8080" ]

  - job_name: 'postgres_exporter'
    static_configs:
      - targets: [ 'postgres_exporter:9187' ]

  - job_name: 'node_exporter'
    static_configs:
      - targets: [ 'node_exporter:9100' ]